---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webcv"
  labels:
    app: "webvc"
    service: "webserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "webcv"
  template:
    metadata:
      labels:
        app: "webcv"
    spec:
      containers:
        - name: "webcv"
          image: "iberejr/webcv:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: "PORT"
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: "webcv"
  labels:
    app: "webvc"
    service: "webserver"
spec:
  selector:
    app: "webcv"
  ports:
  - protocol: "TCP"
    port: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: webcv
  namespace: default
spec:
  entryPoints: 
    - web
    - websecure
  tls:
    domains:
    - main: "*.ibworks.com.br"
  routes:
    - match: Host("cv.ibworks.com.br")
      kind: Rule
      priority: 10
      services:
      - name: webcv
        namespace: default
        passHostHeader: true
        port: 3000

